const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let posts=[],currentCategory='',editingId=null,currentUser=null;
const api=async(url,options={})=>{const r=await fetch(url,{headers:{'Content-Type':'application/json'},...options}),d=await r.json();if(!r.ok)throw Error(d.error||'Etwas ist schiefgelaufen.');return d};
const date=v=>new Intl.DateTimeFormat('de-DE',{dateStyle:'medium'}).format(new Date(v)),esc=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function image(p){return p.imageUrl?`<img class="post-image" src="${esc(p.imageUrl)}" alt="">`:`<div class="symbol">${p.image||'📰'}</div>`}function card(p){return `<article class="card ${p.featured?'featured':''}" data-id="${p.id}">${image(p)}<div class="category">${p.category}</div><h2>${esc(p.title)}</h2><p>${esc(p.excerpt)}</p><div class="meta">${esc(p.author)} · ${date(p.publishedAt)}</div></article>`}
async function loadPosts(){const d=await api('/api/posts'+(currentCategory?`?category=${encodeURIComponent(currentCategory)}`:''));posts=d.posts;$('#news').innerHTML=posts.length?posts.map(card).join(''):'<p class="empty">Zu dieser Kategorie gibt es noch keine Beiträge.</p>';$('#filters').innerHTML=['Alle',...d.categories].map(x=>`<button class="${(x==='Alle'?!currentCategory:currentCategory===x)?'active':''}" data-category="${x}">${x}</button>`).join('');$('#tickerText').textContent=posts[0]?.title||'Aktuelle Meldungen aus AlveroCity';}
function setUser(u){currentUser=u;$('#adminButton').hidden=u?.role!=='admin';$('#accountName').textContent=u?`Hallo, ${u.displayName}`:'';$('#accountButton').textContent=u?'Abmelden':'Anmelden';}
async function refreshUser(){const d=await api('/api/me');setUser(d.user);if(!d.user)$('#welcomeDialog').showModal();}
$('#filters').onclick=e=>{const b=e.target.closest('button');if(b){currentCategory=b.dataset.category==='Alle'?'':b.dataset.category;loadPosts();}};
$('#news').onclick=e=>{const c=e.target.closest('.card');if(!c)return;const p=posts.find(x=>x.id===c.dataset.id);$('#article').innerHTML=`${image(p)}<div class="category">${p.category}</div><h1>${esc(p.title)}</h1><div class="meta">${esc(p.author)} · ${date(p.publishedAt)}</div><p>${esc(p.content).replace(/\n/g,'<br>')}</p>`;$('#articleDialog').showModal()};
$('#year').textContent=new Date().getFullYear();$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());const closeDashboard=()=>$('#dashboardDialog').close();$('#closeDashboard').onclick=closeDashboard;$('#closeDashboardMenu').onclick=closeDashboard;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#dashboardDialog').open)closeDashboard()});$('.menu').onclick=e=>e.currentTarget.classList.toggle('open');
function showDialog(id){$$('dialog').forEach(d=>{if(d.open&&d.id!=='dashboardDialog')d.close()});$(id).showModal();}$('#showLogin').onclick=()=>showDialog('#loginDialog');$('#showRegister').onclick=()=>showDialog('#registerDialog');$('#toRegister').onclick=()=>showDialog('#registerDialog');$('#toLogin').onclick=()=>showDialog('#loginDialog');
$('#accountButton').onclick=async()=>{if(currentUser){await api('/api/logout',{method:'POST'});setUser(null);$('#welcomeDialog').showModal();}else showDialog('#loginDialog')};
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});setUser(d.user);$('#loginDialog').close();$('#welcomeDialog').close();}catch(x){$('#loginError').textContent=x.message}};
$('#registerForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/register',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});setUser(d.user);$('#registerDialog').close();$('#welcomeDialog').close();}catch(x){$('#registerError').textContent=x.message}};
$('#adminButton').onclick=()=>{if(currentUser?.role==='admin'){$('#welcome').textContent=`Willkommen, ${currentUser.displayName}`;$('#dashboardDialog').showModal();loadAdminPosts();}};$('#logoutButton').onclick=async()=>{await api('/api/logout',{method:'POST'});setUser(null);$('#dashboardDialog').close();$('#welcomeDialog').showModal()};
async function loadAdminPosts(){const d=await api('/api/admin/posts');$('#adminPosts').innerHTML=`<div class="admin-list">${d.posts.map(p=>`<div class="admin-row">${image(p)}<div class="admin-post-title"><b>${esc(p.title)}</b><span>${p.category} · ${date(p.publishedAt)}</span></div><div class="actions"><button class="minor" data-edit="${p.id}">Bearbeiten</button><button class="minor danger" data-delete="${p.id}">Löschen</button></div></div>`).join('')||'<p class="empty">Noch keine Beiträge vorhanden.</p>'}</div>`}
function resetUpload(url=''){const preview=$('#uploadPreview');preview.hidden=!url;preview.src=url;$('#postForm').imageUrl.value=url;$('#uploadHint').textContent=url?'Bild ausgewählt – zum Ersetzen ziehen oder klicken':'Bild hierher ziehen oder klicken';}async function upload(file){if(!file)return;if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)||file.size>5*1024*1024){$('#postError').textContent='Bitte ein Bild bis maximal 5 MB (PNG, JPG, WEBP oder GIF) wählen.';return;}$('#uploadHint').textContent='Bild wird hochgeladen …';const dataUrl=await new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)});try{const d=await api('/api/admin/uploads',{method:'POST',body:JSON.stringify({dataUrl})});resetUpload(d.imageUrl);}catch(x){$('#postError').textContent=x.message;resetUpload();}}
$('#dropzone').onclick=()=>$('#imageInput').click();$('#imageInput').onchange=e=>upload(e.target.files[0]);['dragenter','dragover'].forEach(n=>$('#dropzone').addEventListener(n,e=>{e.preventDefault();$('#dropzone').classList.add('drag')}));['dragleave','drop'].forEach(n=>$('#dropzone').addEventListener(n,e=>{e.preventDefault();$('#dropzone').classList.remove('drag')}));$('#dropzone').addEventListener('drop',e=>upload(e.dataTransfer.files[0]));
$('#newPost').onclick=()=>openEditor();function openEditor(p){editingId=p?.id||null;$('#editorTitle').textContent=p?'Beitrag bearbeiten':'Neuer Beitrag';const f=$('#postForm');f.reset();if(p)Object.entries(p).forEach(([k,v])=>{if(f.elements[k]&&k!=='imageUrl')f.elements[k].type==='checkbox'?f.elements[k].checked=v:f.elements[k].value=v});resetUpload(p?.imageUrl||'');$('#postError').textContent='';$('#editorDialog').showModal()}
$('#adminPosts').onclick=async e=>{if(e.target.dataset.edit){const d=await api('/api/admin/posts');openEditor(d.posts.find(p=>p.id===e.target.dataset.edit));}if(e.target.dataset.delete&&confirm('Diesen Beitrag wirklich löschen?')){await api('/api/admin/posts/'+e.target.dataset.delete,{method:'DELETE'});loadAdminPosts();loadPosts();}};
$('#postForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));f.featured=e.target.featured.checked;try{await api(editingId?'/api/admin/posts/'+editingId:'/api/admin/posts',{method:editingId?'PUT':'POST',body:JSON.stringify(f)});$('#editorDialog').close();loadAdminPosts();loadPosts();}catch(x){$('#postError').textContent=x.message}};
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const admins=b.dataset.tab==='admins';$('#adminsPanel').hidden=!admins;$('#adminPosts').hidden=admins;$('#newPost').style.display=admins?'none':'';if(admins)loadAdmins()});
async function loadAdmins(){const d=await api('/api/admin/admins');$('#adminsPanel').innerHTML=`<div class="admin-top"><div><p>BENUTZER</p><h2>Administratoren</h2></div><button class="primary" id="newAdmin">+ Admin hinzufügen</button></div><div class="admin-list">${d.admins.map(a=>`<div class="admin-row"><div class="symbol">👤</div><div><h3>${esc(a.displayName)}</h3><small>@${esc(a.username)}</small></div><div class="actions"><button class="minor danger" data-remove-admin="${a.id}">Entfernen</button></div></div>`).join('')}</div>`;$('#newAdmin').onclick=()=>{$('#adminForm').reset();$('#adminError').textContent='';$('#adminDialog').showModal()}}
$('#adminsPanel').onclick=async e=>{if(e.target.dataset.removeAdmin&&confirm('Diesen Admin wirklich entfernen?'))try{await api('/api/admin/admins/'+e.target.dataset.removeAdmin,{method:'DELETE'});loadAdmins()}catch(x){alert(x.message)}};$('#adminForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/admins',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});$('#adminDialog').close();loadAdmins()}catch(x){$('#adminError').textContent=x.message}};
loadPosts();refreshUser();
