const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const PORT = process.env.PORT || 3000, ROOT = __dirname, DATA_FILE = path.join(ROOT, 'data.json'), UPLOAD_DIR = path.join(ROOT, 'public', 'uploads');
const sessions = new Map(), categories = ['Staatlich','Polizei','UKD','BF/FF','Militär','Mechaniker','Crime'];
fs.mkdirSync(UPLOAD_DIR, {recursive:true});
const hash = (password, salt = crypto.randomBytes(16).toString('hex')) => `${salt}:${crypto.scryptSync(password,salt,64).toString('hex')}`;
const matches = (password, saved) => { const [salt, expected] = saved.split(':'); const got=crypto.scryptSync(password,salt,64).toString('hex'); return crypto.timingSafeEqual(Buffer.from(expected,'hex'),Buffer.from(got,'hex')); };
function initialData(){return {users:[{id:crypto.randomUUID(),username:'admin',displayName:'AC News Redaktion',role:'admin',password:hash(process.env.ADMIN_PASSWORD||'ACNews1'),createdAt:new Date().toISOString()}],posts:[{id:crypto.randomUUID(),title:'Großeinsatz in der Innenstadt: Behörden ziehen Bilanz',excerpt:'Nach einem umfangreichen Einsatz am Abend melden die Einsatzkräfte eine ruhige Lage und bedanken sich bei allen Beteiligten.',content:'Die Behörden waren am Abend mit einem größeren Aufgebot in der Innenstadt im Einsatz. Nach Abschluss der Maßnahmen konnte die Lage beruhigt werden. Weitere Informationen folgen, sobald diese bestätigt sind.',category:'Polizei',author:'AC News Redaktion',image:'🚔',imageUrl:'',featured:true,publishedAt:new Date().toISOString()},{id:crypto.randomUUID(),title:'Das Militär verstärkt seine Reihen',excerpt:'Disziplin, Teamgeist und Verantwortung: Die Streitkräfte suchen engagierte neue Mitglieder.',content:'Interessierte Bürgerinnen und Bürger können sich ab sofort bei der Militärverwaltung informieren.',category:'Militär',author:'AC News Redaktion',image:'🪖',imageUrl:'',featured:false,publishedAt:new Date(Date.now()-86400000).toISOString()}]};}
function save(data){fs.writeFileSync(DATA_FILE,JSON.stringify(data,null,2));}
function load(){if(!fs.existsSync(DATA_FILE))save(initialData());const data=JSON.parse(fs.readFileSync(DATA_FILE,'utf8'));if(!data.users){data.users=(data.admins||[]).map(a=>({...a,role:'admin'}));delete data.admins;const old=data.users.find(u=>u.username==='admin');if(old){old.password=hash(process.env.ADMIN_PASSWORD||'ACNews1');old.displayName='AC News Redaktion';}save(data);}return data;}
function send(res,code,body,type='application/json'){res.writeHead(code,{'Content-Type':`${type}; charset=utf-8`,'Cache-Control':'no-store'});res.end(type==='application/json'?JSON.stringify(body):body);}
function cookie(req){return Object.fromEntries((req.headers.cookie||'').split(';').map(v=>v.trim().split('=').map(decodeURIComponent)).filter(v=>v.length===2));}
function user(req){const session=sessions.get(cookie(req).session);return session?load().users.find(account=>account.id===session.id)||null:null;}
function requireAdmin(req,res){const u=user(req);if(!u||u.role!=='admin'){send(res,403,{error:'Dieser Bereich ist nur für Administratoren verfügbar.'});return null;}return u;}
function body(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>8*1024*1024)req.destroy();});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{});}catch{reject();}});req.on('error',reject);});}
function safeUser(u){const{password,...safe}=u;return safe;}
function cleanPost(p){return {title:String(p.title||'').trim(),excerpt:String(p.excerpt||'').trim(),content:String(p.content||'').trim(),category:categories.includes(p.category)?p.category:'Staatlich',author:String(p.author||'').trim(),image:String(p.image||'📰').trim().slice(0,8),imageUrl:String(p.imageUrl||'').startsWith('/uploads/')?String(p.imageUrl):'',featured:Boolean(p.featured)};}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host}`),route=url.pathname;
if(route==='/api/posts'&&req.method==='GET'){const c=url.searchParams.get('category');return send(res,200,{posts:load().posts.filter(p=>!c||p.category===c).sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt)),categories});}
if(route==='/api/me'&&req.method==='GET')return send(res,200,{user:user(req)?safeUser(user(req)):null});
if(route==='/api/register'&&req.method==='POST'){try{const{username,displayName,password}=await body(req);if(!/^[a-zA-Z0-9_.-]{3,30}$/.test(String(username))||String(password).length<8)return send(res,400,{error:'Benutzername: 3–30 Zeichen; Passwort: mindestens 8 Zeichen.'});const data=load();if(data.users.some(u=>u.username.toLowerCase()===String(username).toLowerCase()))return send(res,409,{error:'Dieser Benutzername ist bereits vergeben.'});const account={id:crypto.randomUUID(),username:String(username),displayName:String(displayName||username).slice(0,50),role:'member',password:hash(String(password)),createdAt:new Date().toISOString()};data.users.push(account);save(data);const token=crypto.randomBytes(32).toString('hex');sessions.set(token,safeUser(account));res.setHeader('Set-Cookie',`session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800`);return send(res,201,{user:safeUser(account)});}catch{return send(res,400,{error:'Ungültige Eingabe.'});}}
if(route==='/api/login'&&req.method==='POST'){try{const{username,password}=await body(req),account=load().users.find(u=>u.username.toLowerCase()===String(username).toLowerCase());if(!account||!matches(String(password),account.password))return send(res,401,{error:'Benutzername oder Passwort ist falsch.'});const token=crypto.randomBytes(32).toString('hex');sessions.set(token,safeUser(account));res.setHeader('Set-Cookie',`session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800`);return send(res,200,{user:safeUser(account)});}catch{return send(res,400,{error:'Ungültige Eingabe.'});}}
if(route==='/api/logout'&&req.method==='POST'){sessions.delete(cookie(req).session);res.setHeader('Set-Cookie','session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');return send(res,200,{ok:true});}
if(route==='/api/admin/uploads'&&req.method==='POST'){if(!requireAdmin(req,res))return;try{const{dataUrl}=await body(req),match=/^data:(image\/(?:png|jpeg|webp|gif));base64,([A-Za-z0-9+/=]+)$/.exec(String(dataUrl));if(!match)return send(res,400,{error:'Erlaubt sind PNG, JPG, WEBP und GIF.'});const file=Buffer.from(match[2],'base64');if(file.length>5*1024*1024)return send(res,400,{error:'Das Bild darf maximal 5 MB groß sein.'});const ext={'image/png':'.png','image/jpeg':'.jpg','image/webp':'.webp','image/gif':'.gif'}[match[1]],filename=`${crypto.randomUUID()}${ext}`;fs.writeFileSync(path.join(UPLOAD_DIR,filename),file);return send(res,201,{imageUrl:`/uploads/${filename}`});}catch{return send(res,400,{error:'Bild konnte nicht verarbeitet werden.'});}}
if(route==='/api/admin/posts'&&req.method==='GET'){if(!requireAdmin(req,res))return;return send(res,200,{posts:load().posts.sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt))});}
if(route==='/api/admin/posts'&&req.method==='POST'){const u=requireAdmin(req,res);if(!u)return;try{const p=cleanPost(await body(req));if(!p.title||!p.excerpt||!p.content)return send(res,400,{error:'Titel, Kurztext und Inhalt sind Pflicht.'});const data=load(),post={...p,id:crypto.randomUUID(),author:p.author||u.displayName,publishedAt:new Date().toISOString()};data.posts.push(post);save(data);return send(res,201,{post});}catch{return send(res,400,{error:'Ungültige Eingabe.'});}}
if(route.startsWith('/api/admin/posts/')&&req.method==='PUT'){if(!requireAdmin(req,res))return;try{const data=load(),i=data.posts.findIndex(p=>p.id===route.split('/').pop());if(i<0)return send(res,404,{error:'Beitrag nicht gefunden.'});const p=cleanPost(await body(req));if(!p.title||!p.excerpt||!p.content)return send(res,400,{error:'Titel, Kurztext und Inhalt sind Pflicht.'});data.posts[i]={...data.posts[i],...p};save(data);return send(res,200,{post:data.posts[i]});}catch{return send(res,400,{error:'Ungültige Eingabe.'});}}
if(route.startsWith('/api/admin/posts/')&&req.method==='DELETE'){if(!requireAdmin(req,res))return;const data=load(),id=route.split('/').pop();data.posts=data.posts.filter(p=>p.id!==id);save(data);return send(res,200,{ok:true});}
if(route==='/api/admin/admins'&&req.method==='GET'){if(!requireAdmin(req,res))return;return send(res,200,{admins:load().users.filter(u=>u.role==='admin').map(safeUser)});}
if(route==='/api/admin/admins'&&req.method==='POST'){if(!requireAdmin(req,res))return;try{const{username,displayName,password}=await body(req);if(!/^[a-zA-Z0-9_.-]{3,30}$/.test(String(username))||String(password).length<8)return send(res,400,{error:'Benutzername: 3–30 Zeichen; Passwort: mindestens 8 Zeichen.'});const data=load();if(data.users.some(u=>u.username.toLowerCase()===String(username).toLowerCase()))return send(res,409,{error:'Dieser Benutzername ist bereits vergeben.'});const admin={id:crypto.randomUUID(),username:String(username),displayName:String(displayName||username),role:'admin',password:hash(String(password)),createdAt:new Date().toISOString()};data.users.push(admin);save(data);return send(res,201,{admin:safeUser(admin)});}catch{return send(res,400,{error:'Ungültige Eingabe.'});}}
if(route.startsWith('/api/admin/admins/')&&req.method==='DELETE'){const u=requireAdmin(req,res);if(!u)return;const id=route.split('/').pop(),data=load();if(id===u.id)return send(res,400,{error:'Du kannst dich nicht selbst entfernen.'});if(data.users.filter(a=>a.role==='admin').length<2)return send(res,400,{error:'Mindestens ein Admin muss bestehen bleiben.'});data.users=data.users.filter(a=>a.id!==id);save(data);return send(res,200,{ok:true});}
const file=route==='/'?path.join(ROOT,'public','index.html'):path.join(ROOT,'public',route),safe=path.normalize(file);if(!safe.startsWith(path.join(ROOT,'public'))||!fs.existsSync(safe)||fs.statSync(safe).isDirectory())return send(res,404,'Nicht gefunden','text/plain');const types={'.html':'text/html','.css':'text/css','.js':'application/javascript','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.gif':'image/gif'};return send(res,200,fs.readFileSync(safe),types[path.extname(safe).toLowerCase()]||'application/octet-stream');});
server.listen(PORT,()=>console.log(`AC News läuft auf http://localhost:${PORT}`));
